// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpWTZQhDqBbA_mdKrT1-uU9JsnWLetqaw',
    appId: '1:855782245192:web:d564d501670feb1683e97d',
    messagingSenderId: '855782245192',
    projectId: 'bookin-fa09e',
    authDomain: 'bookin-fa09e.firebaseapp.com',
    storageBucket: 'bookin-fa09e.firebasestorage.app',
    measurementId: 'G-ZLX1XG7JL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVSAZgE70qHz-6mf6vIBEKGzSX14lYf8',
    appId: '1:855782245192:android:51ae0766f24a8be483e97d',
    messagingSenderId: '855782245192',
    projectId: 'bookin-fa09e',
    storageBucket: 'bookin-fa09e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ftnyqllUBBVuEimghLQ4ZtH-12EJ9co',
    appId: '1:855782245192:ios:b8bc4fccc10b69bd83e97d',
    messagingSenderId: '855782245192',
    projectId: 'bookin-fa09e',
    storageBucket: 'bookin-fa09e.firebasestorage.app',
    iosBundleId: 'com.example.bookin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ftnyqllUBBVuEimghLQ4ZtH-12EJ9co',
    appId: '1:855782245192:ios:b8bc4fccc10b69bd83e97d',
    messagingSenderId: '855782245192',
    projectId: 'bookin-fa09e',
    storageBucket: 'bookin-fa09e.firebasestorage.app',
    iosBundleId: 'com.example.bookin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpWTZQhDqBbA_mdKrT1-uU9JsnWLetqaw',
    appId: '1:855782245192:web:2aeb444b37fd019583e97d',
    messagingSenderId: '855782245192',
    projectId: 'bookin-fa09e',
    authDomain: 'bookin-fa09e.firebaseapp.com',
    storageBucket: 'bookin-fa09e.firebasestorage.app',
    measurementId: 'G-E6Y9V71LLT',
  );
}
